spring:
  datasource:
    url: "jdbc:postgresql://ilumina-db-dev-qa-instance-1.cl4qq8c0s5we.ap-south-1.rds.amazonaws.com:5432/iluminaqa?currentSchema=fhir"
    username: qa
    password: Iluminaqa*123
    driverClassName: org.postgresql.Driver
    # database connection pool size
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
