spring:
  datasource:
    url: "jdbc:postgresql://ilumina-db-uat-instance-1.cpcu8wm0200j.ap-south-1.rds.amazonaws.com:5432/iluminauat?currentSchema=fhir"
    username: uat
    password: Iluminauat*123
    driverClassName: org.postgresql.Driver
    # database connection pool size
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
